### ISSUE TITLE
WebDriverJS: SyntaxError

### ISSUE THREAD

**Issue by ppasler** [seibert-media/confluence-protractor-base#3]
When running `webdriver-manager update` 
```
SyntaxError: Unexpected token ...
node_modules\webdriver-manager\built\lib\cli\logger.js:66
    info(...msgs) {
         ^^^
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\wuyang\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\built\
lib\cli\index.js:8:10)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
```
See https://github.com/angular/protractor/issues/4001.

**Comment by ppasler** [comment]
Update Node and npm (for Ubuntu 16.04 Node 7.6.0 and npm 4.1.2 worked).
